[project]
name = "research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "instructor>=1.15.4",
    "langgraph>=1.2.11",
    "openai>=2.54.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
    "tavily-python>=0.8.0",
]

[project.scripts]
research-agent = "research_agent:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
